--
-- require("lazy").setup(plugins, {
--     ui = { border = "rounded" },
--     rocks = {
--         enabled = false,
--     },
--     performance = {
--         rtp = {
--             disabled_plugins = {
--                 "gzip",
--                 "netrwPlugin",
--                 "rplugin",
--                 "tarPlugin",
--                 "tohtml",
--                 "tutor",
--                 "zipPlugin",
--             },
--         },
--     },
-- })
