-- -- KANAGAWA
-- vim.pack.add({ "https://github.com/rebelot/kanagawa.nvim" })
--
-- -- Color theme
-- require("kanagawa").setup({
--     keywordStyle = { italic = false },
--     colors = {
--         theme = {
--             all = {
--                 ui = {
--                     bg_gutter = "none",
--                 },
--             },
--         },
--     },
--     overrides = function(colors)
--         local theme = colors.theme
--         local makeDiagnosticColor = function(color)
--             local c = require("kanagawa.lib.color")
--             return { fg = color, bg = c(color):blend(theme.ui.bg, 0.95):to_hex() }
--         end
--
--         return {
--             -- Right-click menu (Pmenu) - darker version
--             Pmenu = { fg = theme.ui.shade0, bg = theme.ui.bg_p1 }, -- add `blend = vim.o.pumblend` to enable transparency
--             PmenuSel = { fg = "NONE", bg = theme.ui.bg_p2 },
--             PmenuSbar = { bg = theme.ui.bg_m1 },
--             PmenuThumb = { bg = theme.ui.bg_p2 },
--             BlinkCmpMenuBorder = { fg = "", bg = "" },
--
--             NormalFloat = { bg = "none" },
--             FloatBorder = { bg = "none" },
--             FloatTitle = { bg = "none" },
--             NormalDark = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
--
--             -- Popular plugins that open floats will link to NormalFloat by default;
--             -- set their background accordingly if you wish to keep them dark and borderless
--             LazyNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },
--             MasonNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },
--
--             DiagnosticVirtualTextHint = makeDiagnosticColor(theme.diag.hint),
--             DiagnosticVirtualTextInfo = makeDiagnosticColor(theme.diag.info),
--             DiagnosticVirtualTextWarn = makeDiagnosticColor(theme.diag.warning),
--             DiagnosticVirtualTextError = makeDiagnosticColor(theme.diag.error),
--         }
--     end,
-- })
-- vim.cmd("colorscheme kanagawa-dragon")

-- VAGUE
-- vim.pack.add({ "https://github.com/vague-theme/vague.nvim" })
-- vim.cmd.colorscheme("vague")
